sonar.organization=bikalpakc
sonar.projectKey=bikalpakc_TRL-LinkShortener-Backend

# Address of the SonarCloud server
sonar.host.url=https://sonarcloud.io

# Path to the source code (current directory)
sonar.sources=.

# Telling SonarCloud to ignore migrations and the virtual environment
sonar.exclusions=**/migrations/**, **/env/**, **/venv/**, static/**, staticfiles/**

# Language settings
sonar.python.version=3
sonar.language=py