# Generated by Django 5.2.14 on 2026-05-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_click_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
