name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Static Code Analysis (SonarCloud)
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 

      # 4. Build and Tag
      - name: Build and Tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: trl-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
      # 5. Security Scan (Trivy)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.24.0 
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/trl-backend:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 6. Push to ECR
      - name: Push image to ECR
        if: success()
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: trl-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest



# There is a "glitch" in AWS right now. When the pipeline downloads the Task Definition from AWS, AWS includes a new experimental field called enableFaultInjection. However, when the pipeline tries to send that same recipe back to AWS to update it, the AWS deployment tool says, "I don't recognize this new field yet!" and crashes.
# To fix this, we need to add a "Cleaning" step. We are using a tool called jq (which is built into GitHub Actions) to strip out that problematic field (and a few other metadata fields AWS doesn't like) before we deploy.

      # 7. WEB SERVICE DEPLOYMENT
      - name: Download and Clean Task Definition (Web)
        run: |
          aws ecs describe-task-definition --task-definition trl-web-task --query taskDefinition > raw-task-def-web.json
          cat raw-task-def-web.json | jq 'del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .compatibilities, .requiresAttributes, .enableFaultInjection)' > task-def-web.json

      - name: Fill in the new image ID in the Amazon ECS task definition (Web)
        id: task-def-web
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-web.json
          container-name: web
          image: ${{ steps.login-ecr.outputs.registry }}/trl-backend:latest

      - name: Deploy Amazon ECS task definition (Web)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-web.outputs.task-definition }}
          service: trl-web-service
          cluster: trl-cluster
          wait-for-service-stability: true

      # 8. WORKER & BEAT SERVICE DEPLOYMENT
      - name: Download and Clean Task Definition (Worker)
        run: |
          aws ecs describe-task-definition --task-definition trl-worker-task --query taskDefinition > raw-task-def-worker.json
          cat raw-task-def-worker.json | jq 'del(.taskDefinitionArn, .revision, .status, .registeredAt, .registeredBy, .compatibilities, .requiresAttributes, .enableFaultInjection)' > task-def-worker.json

      - name: Update 'worker' container image
        id: render-worker
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-def-worker.json
          container-name: Celery-Worker
          image: ${{ steps.login-ecr.outputs.registry }}/trl-backend:latest

      - name: Update 'beat' container image
        id: render-beat
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-worker.outputs.task-definition }}
          container-name: Celery-Beat
          image: ${{ steps.login-ecr.outputs.registry }}/trl-backend:latest

      - name: Deploy Amazon ECS task definition (Worker Service)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-beat.outputs.task-definition }}
          service: trl-worker-service
          cluster: trl-cluster
          wait-for-service-stability: true